services:
  atelier-docker-2:
    image: atelier-docker-2
    ports:
      - 3001:3001
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app-network
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=atelierdocker
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
